version: "3.7"

services:
  traefik:
    image: traefik:2.1.8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - "60666:8080"
    networks:
      - cursodegit
  cursodegit:
    image: cursodegit/web:latest
    networks:
      - cursodegit
    deploy:
      labels:
        - traefik.discoverable=yes
        - traefik.http.routers.cursodegit.entryPoints=web-secure
        - traefik.http.routers.cursodegit.rule=Host(`www.cursodegit.com`)
        - traefik.http.routers.cursodegit.priority=50
        #- traefik.http.routers.cursodegit.tls.certResolver=letsencrypt
        - traefik.http.routers.cursodegit.service=cursodegit-service
        - traefik.http.services.cursodegit-service.loadbalancer.server.port=80
networks:
  cursodegit:
    external: true
